package com.bondar.urlshortener.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShortUrlAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortUrlAllPropertiesEquals(ShortUrl expected, ShortUrl actual) {
        assertShortUrlAutoGeneratedPropertiesEquals(expected, actual);
        assertShortUrlAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortUrlAllUpdatablePropertiesEquals(ShortUrl expected, ShortUrl actual) {
        assertShortUrlUpdatableFieldsEquals(expected, actual);
        assertShortUrlUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortUrlAutoGeneratedPropertiesEquals(ShortUrl expected, ShortUrl actual) {
        assertThat(actual)
            .as("Verify ShortUrl auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortUrlUpdatableFieldsEquals(ShortUrl expected, ShortUrl actual) {
        assertThat(actual)
            .as("Verify ShortUrl relevant properties")
            .satisfies(a -> assertThat(a.getOriginalUrl()).as("check originalUrl").isEqualTo(expected.getOriginalUrl()))
            .satisfies(a -> assertThat(a.getShortCode()).as("check shortCode").isEqualTo(expected.getShortCode()))
            .satisfies(a -> assertThat(a.getCreatedAt()).as("check createdAt").isEqualTo(expected.getCreatedAt()))
            .satisfies(a -> assertThat(a.getExpiryAt()).as("check expiryAt").isEqualTo(expected.getExpiryAt()))
            .satisfies(a -> assertThat(a.getActive()).as("check active").isEqualTo(expected.getActive()))
            .satisfies(a -> assertThat(a.getAccessCount()).as("check accessCount").isEqualTo(expected.getAccessCount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShortUrlUpdatableRelationshipsEquals(ShortUrl expected, ShortUrl actual) {
        // empty method
    }
}
